set-option -g default-shell /bin/zsh

set-option -g mode-keys vi
set-option -g mouse on
set -sg escape-time 10

# vim-like pane selecting
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R # NOTE: this overwrites go to last window

# overwrite `p` to be the **last** window instead of previous
bind-key p last-window

# to allow yazi to work
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
