set-option -g default-shell /bin/zsh

set-option -g mode-keys vi
set-option -g mouse on
set-option -sg escape-time 4
set-option -g focus-events on
set-option -g extended-keys on

# vim-like pane selecting
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R # NOTE: this overwrites go to last window
bind-key o last-window

# make word selection target paths naturally
set-option -g word-separators " |{}()[]<>`='!^&*\\\""

# to allow yazi to work
set-option -g allow-passthrough on
set-option -ga update-environment TERM
set-option -ga update-environment TERM_PROGRAM

bind-key '"' split-window -v -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"

# plugin specific commands
set-option -g status-right '%a %Y-%m-%d %H:%M'
# set-option -g status-style bg=colour235,fg=white

# Background changes to red when prefix is active, black when not
set-option -g status-style "bg=#{?client_prefix,red,black}"

# List of plugins
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'tmux-plugins/tmux-resurrect'
set-option -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set-option -g @plugin 'wfxr/tmux-power'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# plugin specific commands
set -g @tmux_power_theme 'moon'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
