# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/neovim
#
# install neovim through brew
- name: Install neovim using Homebrew
  community.general.homebrew:
    name:
      - neovim
    state: present

# --- Dependencies lazyvim needs ---
- name: Install LazyVim dependencies
  ansible.builtin.package:
    name:
      - git
      - curl
      - ripgrep       # lazyvim uses this for search
      - fd-find       # lazyvim uses this for file finding
      - unzip
      - tree-sitter-cli
    state: present
  become: true

# # --- Bootstrap lazyvim config ---
# - name: Ensure nvim config directory exists
#   ansible.builtin.file:
#     path: "{{ neovim_config_dir }}"
#     state: directory
#     owner: "{{ neovim_user }}"
#     mode: '0755'
