# SPDX-License-Identifier: MIT-0
---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: ansible_pkg_mgr == 'apt'

- name: Install system packages
  become: true
  ansible.builtin.package:
    name: "{{ common_system_packages }}"
    state: present

# --- Set zsh as default shell ---
- name: Set zsh as default shell for user
  ansible.builtin.user:
    name: "{{ common_user }}"
    shell: /bin/zsh

- name: Run Homebrew tasks
  ansible.builtin.import_tasks: homebrew.yml
