# SPDX-License-Identifier: MIT-0
---
- name: Install common tools
  become: true
  ansible.builtin.package:
    name:
      - curl
      - git
      - zsh
      - coreutils
      - build-essential
      - stow
      - neovim # nice to have at system level
    state: present

# --- Set zsh as default shell ---
- name: Set zsh as default shell for user
  ansible.builtin.user:
    name: "{{ common_user }}"
    shell: /bin/zsh

- name: Check if Homebrew is installed
  ansible.builtin.stat:
    path: "{{ item }}"
  with_items:
    - /opt/homebrew/bin/brew
    - /usr/local/bin/brew
    - /home/linuxbrew/.linuxbrew/bin/brew
  register: common_brew_check

- name: Set fact if Homebrew exists
  ansible.builtin.set_fact:
    common_brew_installed: "{{ common_brew_check.results | map(attribute='stat.exists') | list is any }}"

- name: Install Homebrew
  become: true
  become_user: "{{ common_user }}"
  ansible.builtin.shell:
    cmd: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when: not common_brew_installed
  changed_when: true

- name: Install common homebrew tools
  become: false
  community.general.homebrew:
    name:
      - pyenv
      - cheat
      - fd
      - tmux
      - podman
      - pipx
      - bat
    state: present
