common_system_packages:
  - curl
  - git
  - zsh
  - coreutils
  - nodejs
  - npm
  - make
  - automake
  - cmake
  - gcc
  - gcc-c++
  - kernel-devel
  - stow
  - neovim # nice to have at system level

common_system_packages_extras: []
