- name: Apply baseline system-level changes
  hosts:
    - raspberrypis
    - stations
  become: true
  roles:
    - common

- name: Apply configs
  hosts:
    - raspberrypis
    - stations
  roles:
    - zsh
    - neovim
    - mydotfiles
  tags:
    - configs
