# SPDX-License-Identifier: MIT-0
---
mydotfiles_user: jahir

mydotfiles_repo: "git@github.com:SciencyBagel/mydotfiles.git"
mydotfiles_repo_dest: "{{ ansible_user_dir }}/mydotfiles"
mydotfiles_repo_home: "{{ mydotfiles_repo_dest }}/home"
