# SPDX-License-Identifier: MIT-0
---
# tasks file for roles/neovim
- name: Install neovim using Homebrew
  community.general.homebrew:
    name:
      - neovim
    state: present

# --- Dependencies lazyvim needs ---
- name: Install LazyVim dependencies
  community.general.homebrew:
    name:
      - neovim
      - git
      - curl
      - ripgrep       # lazyvim uses this for search
      - fd       # lazyvim uses this for file finding
      - unzip
      - tree-sitter-cli
    state: present
  # become: true
  # become_user: "{{ lazyvim_user }}"

# # --- Bootstrap lazyvim config ---
# - name: Ensure nvim config directory exists
#   ansible.builtin.file:
#     path: "{{ lazyvim_config_dir }}"
#     state: directory
#     owner: "{{ lazyvim_user }}"
#     mode: '0755'
